#!/usr/bin/env bash
# Interactive Android version bump: pubspec.yaml + CHANGELOG.md [Unreleased] → new section.
#
# Writes dist/app/release-flags.env for ./scripts/release-android-apk.sh:
#   BUMP_MINIMUM=0  optional update (keep current force-update floor)
#   BUMP_MINIMUM=1  raise minimum to this release (mandatory for older builds)
#
# Usage (from repo root):
#   ./scripts/bump-app-version.sh
#   ./scripts/release-android-apk.sh --build

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PUBSPEC="${REPO_ROOT}/app/pubspec.yaml"
CHANGELOG="${REPO_ROOT}/CHANGELOG.md"
RELEASE_FLAGS="${REPO_ROOT}/dist/app/release-flags.env"

if [[ ! -t 0 ]]; then
    echo "bump-app-version.sh must run interactively (needs a TTY)." >&2
    exit 1
fi

if [[ ! -f "$PUBSPEC" ]]; then
    echo "Missing ${PUBSPEC}" >&2
    exit 1
fi
if [[ ! -f "$CHANGELOG" ]]; then
    echo "Missing ${CHANGELOG}" >&2
    exit 1
fi

CURRENT="$(grep -E '^version:' "$PUBSPEC" | awk '{print $2}')"
if [[ ! "$CURRENT" =~ ^([0-9]+\.[0-9]+\.[0-9]+)\+([0-9]+)$ ]]; then
    echo "Could not parse version from pubspec (expected X.Y.Z+N): ${CURRENT}" >&2
    exit 1
fi

CUR_VERSION="${BASH_REMATCH[1]}"
CUR_BUILD="${BASH_REMATCH[2]}"

IFS='.' read -r _major _minor _patch <<< "$CUR_VERSION"
SUGGEST_VERSION="${_major}.${_minor}.$((_patch + 1))"
SUGGEST_BUILD=$((CUR_BUILD + 1))

echo "Current app version: ${CUR_VERSION}+${CUR_BUILD}"
echo ""

read -rp "New version (${SUGGEST_VERSION}): " NEW_VERSION
NEW_VERSION="${NEW_VERSION:-$SUGGEST_VERSION}"

read -rp "New build number (${SUGGEST_BUILD}): " NEW_BUILD
NEW_BUILD="${NEW_BUILD:-$SUGGEST_BUILD}"

if [[ ! "$NEW_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "Invalid version (use semver X.Y.Z): ${NEW_VERSION}" >&2
    exit 1
fi
if [[ ! "$NEW_BUILD" =~ ^[0-9]+$ ]] || [[ "$NEW_BUILD" -le 0 ]]; then
    echo "Invalid build number: ${NEW_BUILD}" >&2
    exit 1
fi

echo ""
echo "Release type:"
echo "  optional — latest APK only; users above minimum see an optional update prompt"
echo "  forced   — also raise minimum version (blocks older builds until they update)"
read -rp "Force-update users below ${NEW_VERSION}+${NEW_BUILD}? [y/N]: " FORCE_REPLY
FORCE_REPLY="${FORCE_REPLY,,}"

BUMP_MINIMUM=0
if [[ "$FORCE_REPLY" == "y" || "$FORCE_REPLY" == "yes" ]]; then
    BUMP_MINIMUM=1
fi

RELEASE_DATE="$(date +%Y-%m-%d)"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

awk -v ver="$NEW_VERSION" -v dt="$RELEASE_DATE" '
    BEGIN { in_unreleased = 0; unreleased = "" }
    /^## \[Unreleased\]/ {
        print "## [Unreleased]"
        print ""
        in_unreleased = 1
        next
    }
    in_unreleased && /^## / {
        in_unreleased = 0
        print "## [" ver "] - " dt
        sub(/\n+$/, "", unreleased)
        if (unreleased != "") {
            print unreleased
        }
        print ""
        print
        next
    }
    in_unreleased {
        unreleased = unreleased $0 "\n"
        next
    }
    { print }
' "$CHANGELOG" > "$TMP"
mv "$TMP" "$CHANGELOG"
trap - EXIT

if grep -q "^## \\[${NEW_VERSION}\\]" "$CHANGELOG"; then
    SECTION_BODY="$(awk -v ver="$NEW_VERSION" '
        $0 ~ "^## \\[" ver "\\]" { found=1; next }
        found && /^## / { exit }
        found { print }
    ' "$CHANGELOG" | sed '/./,$!d')"
    if [[ -z "${SECTION_BODY//[$'\n\r\t ']/}" ]]; then
        echo ""
        echo "Warning: ## [${NEW_VERSION}] has no release notes yet."
        echo "Add bullets under [Unreleased] before running release-android-apk.sh,"
        echo "or edit CHANGELOG.md manually — import will fail on an empty section."
    fi
fi

sed -i "s/^version: .*/version: ${NEW_VERSION}+${NEW_BUILD}/" "$PUBSPEC"

mkdir -p "$(dirname "$RELEASE_FLAGS")"
cat > "$RELEASE_FLAGS" <<EOF
# Generated by scripts/bump-app-version.sh — read by release-android-apk.sh
BUMP_MINIMUM=${BUMP_MINIMUM}
EOF

echo ""
echo "Updated:"
echo "  ${PUBSPEC} → ${NEW_VERSION}+${NEW_BUILD}"
echo "  ${CHANGELOG} → moved [Unreleased] into [${NEW_VERSION}] - ${RELEASE_DATE}"
echo "  ${RELEASE_FLAGS} → BUMP_MINIMUM=${BUMP_MINIMUM}"
echo ""
if [[ "$BUMP_MINIMUM" -eq 1 ]]; then
    echo "Next: ./scripts/release-android-apk.sh --build"
    echo "      (will pass --bump-minimum to Postgres import)"
else
    echo "Next: ./scripts/release-android-apk.sh --build"
    echo "      (optional update only — minimum version unchanged)"
fi
